# Generated by Django 3.2.7 on 2021-09-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='bio',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
